CheckPoint 5/Sales/WebSales/Controllers/GoodsController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WatcherModel;
using WatcherModel.Repository;

namespace WebSales.Controllers
{
    [Authorize]
    public class GoodsController : Controller
    {        
         // GET: Goods
        private UnitOfWork _unit = new UnitOfWork(new ModelContainer());
        private IRepository<Goods> repo;

        public GoodsController()
        {
            repo=_unit.ReposGoods;
        }

        public ActionResult Index()
        {
            return View(repo.GetAll());
        }

        [HttpPost]
        public ActionResult SearchGoods(string name)
        {
            var goods = repo.SearchFor(a => a.NameGoods.Contains(name)).ToList();
            if (goods.Count <= 0)
            {
                return HttpNotFound();
            }
            return PartialView(goods);
        }
        // GET: Goods/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                var goodsSet = repo.GetById((int)id);
                if (goodsSet == null)
                {
                    return HttpNotFound();
                }
                return View(goodsSet);
            }
        }

        // GET: Goods/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Goods/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "Id,FirstName,SecondName")] Goods goodsSet)
        {
            if (ModelState.IsValid)
            {
                repo.Insert(goodsSet);
                _unit.Save();
                return RedirectToAction("Index");
            }
            return View(goodsSet);
        }

        // GET: Goods/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var goodsSet = repo.GetById((int)id);
            if (goodsSet == null)
            {
                return HttpNotFound();
            }
            return View(goodsSet);
        }

        // POST: Goods/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "Id,NameGoods")] Goods goodsSet)
        {
            if (ModelState.IsValid)
            {
                repo.Update(goodsSet);
                _unit.Save();
                return RedirectToAction("Index");
            }
            return View(goodsSet);
        }

        // GET: Goods/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var goodsSet = repo.GetById((int)id);
            if (goodsSet == null)
            {
                return HttpNotFound();
            }
            return View(goodsSet);
        }

        // POST: Goods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var goodsSet = repo.GetById(id);
                repo.Delete(goodsSet);
                _unit.Save();
                return RedirectToAction("Index");
            }
            catch 
            {
                ViewBag.Error = "No deleted!";
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unit.Dispose();
            }
            base.Dispose(disposing);
        }   
    }
}

CheckPoint 5/Sales/WebSales/Controllers/ReportsController.cs
using System.Linq;
using System.Web.Mvc;
using WatcherModel;
using WatcherModel.Repository;
using WebSales.Models;

namespace WebSales.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork(new ModelContainer());
      
        // GET: Reports
        public ActionResult Index()
        {
            ViewBag.FilterManager = new SelectList(_unit.ReposManager.GetAll().OrderBy(x => x.SecondName), "Id", "SecondName");             
            return View();
        }

        [HttpPost]
        public ActionResult Report(FilterModels filter)
        {
            var query = from tt in _unit.ReposOrder.GetAll()
                        where tt.Date >= filter.DateStart && tt.Date <= filter.DateFinish
                        select tt;
            ReportManagerModels reportManager;
            if (filter.FilterManager!=null)
            {
               reportManager=(from tt in query.Where(x=>x.IdManager == filter.FilterManager)
                         group tt by tt.Manager into g
                         select new ReportManagerModels()
                         {
                             NameManager = g.Key.SecondName,
                             TotalCost = g.Sum(x => x.Cost),
                             TotalSales = g.Count()
                         }).FirstOrDefault();
            }
            else if (filter.FilterGoods != null)
            {
                reportManager = (from tt in query.Where(x => x.IdGoods == filter.FilterGoods)
                                 group tt by tt.Goods into g
                                 select new ReportManagerModels()
                                 {
                                     NameGoods = g.Key.NameGoods,
                                     TotalCost = g.Sum(x => x.Cost),
                                     TotalSales = g.Count()
                                 }).FirstOrDefault();
            }
            else
            {
                reportManager = new ReportManagerModels()
                {
                    NameManager = "All",
                    TotalCost = query.Sum(x => x.Cost),
                    TotalSales = query.Count()
                };
            }            
            return PartialView(reportManager);
        }

        public ActionResult Goods()
        {
            ViewBag.FilterGoods = new SelectList(_unit.ReposGoods.GetAll().OrderBy(x => x.NameGoods), "Id", "NameGoods");
            return View();
        }
    }
}

CheckPoint 5/Sales/WebSales/Views/Reports/Goods.cshtml
@model WebSales.Models.OrderFilterModels
@{
    ViewBag.Title = "Reports Goods";
}

<h2>Reports Goods</h2>
<ul class="nav nav-tabs">
    <li>@Html.ActionLink("Reports manager", "Index", "Reports")</li>
    <li class="active">@Html.ActionLink("Reports goods", "Goods", "Reports")</li>
</ul>

@using (Ajax.BeginForm(new AjaxOptions { Url = Url.Action("Report"), UpdateTargetId = "reportView" }))
{
    <div class="form-inline">
        <label class="control-label">Select goods: </label>
        @Html.DropDownList("FilterGoods", (SelectList)ViewBag.FilterGoods, "All")
        <label class="control-label">From: </label>
        @Html.EditorFor(model => model.DateStart, new { htmlAttributes = new { @class = "form-control" } })
        <label class="control-label">To: </label>
        @Html.EditorFor(model => model.DateFinish, new { htmlAttributes = new { @class = "form-control" } })
        <input type="submit" value="Ok" />
    </div>
}
@Html.Partial("Report")

CheckPoint 5/Sales/WebSales/Views/Reports/Index.cshtml
@model WebSales.Models.OrderFilterModels
@{
    ViewBag.Title = "Reports";
}

<h2>Reports</h2>
<ul class="nav nav-tabs">
    <li class="active">@Html.ActionLink("Reports manager", "Index", "Reports")</li>
    <li>@Html.ActionLink("Reports goods", "Goods", "Reports")</li>
</ul>

@using (Ajax.BeginForm(new AjaxOptions { Url = Url.Action("Report"), UpdateTargetId = "reportView" }))
{
    <div class="form-inline">
        <label class="control-label">Select mаnager: </label>
        @Html.DropDownList("FilterManager", (SelectList)ViewBag.FilterManager, "All")
        <label class="control-label">From: </label>
        @Html.EditorFor(model => model.DateStart, new { htmlAttributes = new { @class = "form-control" } })
        <label class="control-label">To: </label>
        @Html.EditorFor(model => model.DateFinish, new { htmlAttributes = new { @class = "form-control" } })
        <input type="submit" value="Ok" />
    </div>
}
@Html.Partial("Report")

CheckPoint 5/Sales/WebSales/Views/Reports/Report.cshtml
@model WebSales.Models.ReportManagerModels


<div id="reportView">
@if (Model != null)
{
     <hr />
    <dl class="dl-horizontal">
        @if (Model.NameManager != null) { 
        <dt>
            @Html.DisplayNameFor(model => model.NameManager)            
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameManager) 
        </dd>
        } else{
        <dt>
            @Html.DisplayNameFor(model => model.NameGoods)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameGoods)
        </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.TotalSales) 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalSales)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalCost)
        </dd>
    </dl>
}
</div>