CheckPoint 5/Sales/WebSales/Controllers/GraphicsController.cs
using System.Linq;
using System.Web.Mvc;
using WatcherModel;
using WatcherModel.Repository;
using WebSales.Models;

namespace WebSales.Controllers
{
    [Authorize]
    public class GraphicsController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork(new ModelContainer());
        // GET: Graphics
        public ActionResult Index()
        {
            ViewBag.FilterManager = new SelectList(_unit.ReposManager.GetAll().OrderBy(x => x.SecondName), "Id", "SecondName");
            return View(new FilterModels());
        }
               
        public JsonResult JsonSearch([Bind(Include = "FilterManager,DateStart,DateFinish")] FilterModels filter)//,DateTime dateStart,DateTime DateTimeFinish)
        {
            var idManger = filter.FilterManager;
            var query = from tt in _unit.ReposOrder.GetAll()
                        where tt.Date >= filter.DateStart && tt.Date <= filter.DateFinish
                        select tt;
            if (idManger != null)
            {
                query = query.Where(x => x.IdManager == idManger);
            }
            var zz = (from tt in query
                      let date = tt.Date.Day + "." + tt.Date.Month + "." + tt.Date.Year
                      group tt by date into g
                      select new ChartGoodsDate
                      {
                          DateStr = g.Key,
                          CountGoods = g.Count()
                      }).ToList<ChartGoodsDate>().OrderBy(x => x.Date);
            return Json(zz);//, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Pie()
        {
            ViewBag.TotalCostOrSales = new SelectList(new[] { "Total cost", "Total sales" });
            return View(new FilterModels());
        }

        public JsonResult JsonPie(string totalCostOrSales, FilterModels filter)//[Bind(Include = "DateStart,DateFinish")] FilterModels filter,int TotalCostOrSales
        {
            var zz = (from tt in _unit.ReposOrder.GetAll()
                      where tt.Date >= filter.DateStart && tt.Date <= filter.DateFinish
                      group tt by tt.Manager into g
                      select new ChartDataPie(totalCostOrSales,g.Sum(x=>x.Cost),g.Count())
                      {
                          LastNameManager = g.Key.SecondName
                      }).ToList<ChartDataPie>();
           return Json(zz, JsonRequestBehavior.AllowGet);
        }
    }
}

CheckPoint 5/Sales/WebSales/Views/Graphics/Index.cshtml
@model WebSales.Models.FilterModels
@{
    ViewBag.Title = "Index";
}

<h2>Graphics</h2>
<ul class="nav nav-tabs">
    <li class="active">@Html.ActionLink( "Chart column", "Index", "Graphics")</li>
    <li>@Html.ActionLink("Chart pie", "Pie", "Graphics")</li>
</ul>


@using (Ajax.BeginForm(new AjaxOptions { OnSuccess = "OnSuccess", Url = Url.Action("JsonSearch") }))
{
    <div class="form-inline">
       <label class="control-label">Select mаnager: </label>
        @Html.DropDownList("FilterManager", (SelectList)ViewBag.FilterManager, "All")
        <label class="control-label">From: </label>
        @Html.EditorFor(model => model.DateStart, new { htmlAttributes = new { @class = "form-control" } })
        <label class="control-label">To: </label>
        @Html.EditorFor(model => model.DateFinish, new { htmlAttributes = new { @class = "form-control" } })
        <input type="submit" value="Paint" />        
    </div>
}

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", { packages: ["corechart"] });
</script>

<script type="text/javascript">
    $(document).ready(
        $.ajax({
            type: 'POST',
            dataType: 'json',
            contentType: 'application/json',
            url: '@Url.Action("JsonSearch")',
            data: '{}',
            success: function (chartsdata) { OnSuccess(chartsdata) }
        }));

    function OnSuccess(chartsdata) {
        var data = new window.google.visualization.DataTable();
        data.addColumn('string', 'Date');
        data.addColumn('number', 'Count goods');
        for (var i = 0; i < chartsdata.length; i++) {
            data.addRow([chartsdata[i].DateStr, chartsdata[i].CountGoods]);
        }
        // Instantiate and draw our chart, passing in some options
        var chart = new window.google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data,
          {
              title: "Statistics sectional managers",
              position: "top",
              fontsize: "14px",
              chartArea: { width: '50%' }
          });
    }
</script>
<div id="chart_div" style="height: 350px;"></div>

CheckPoint 5/Sales/WebSales/Views/Graphics/Pie.cshtml
@model WebSales.Models.FilterModels
@{
    ViewBag.Title = "Pie";
}

<h2>Graphics</h2>
<ul class="nav nav-tabs">
    <li >@Html.ActionLink("Chart column", "Index", "Graphics")</li>
    <li class="active">@Html.ActionLink("Chart pie", "Pie", "Graphics")</li>
</ul>

@using (Ajax.BeginForm(new AjaxOptions { OnSuccess = "OnSuccess", Url = Url.Action("JsonPie") }))
{
    <div class="form-inline">
        <label class="control-label">Statistics in the context of: </label>
        @Html.DropDownList("TotalCostOrSales", (SelectList)ViewBag.TotalCostOrSales)
        <label class="control-label">From: </label>
        @Html.EditorFor(model => model.DateStart, new { htmlAttributes = new { @class = "form-control" } })
        <label class="control-label">To: </label>
        @Html.EditorFor(model => model.DateFinish, new { htmlAttributes = new { @class = "form-control" } })
        <input type="submit" value="Paint" />
    </div>
}

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", { packages: ["corechart"] });
</script>


<script type="text/javascript">
    $(document).ready(
       $.ajax({
           type: 'POST',
           dataType: 'json',
           contentType: 'application/json',
           url: '@Url.Action("JsonPie")',
           data: '{}',
           success: function (chartsdata) { OnSuccess(chartsdata) }
       }));

     function OnSuccess(chartsdata) {
               
                var data = new window.google.visualization.DataTable();
                data.addColumn('string', 'Manager');
                data.addColumn('number', 'Total Sum');

                for (var i = 0; i < chartsdata.length; i++) {
                    data.addRow([chartsdata[i].LastNameManager, chartsdata[i].TotalCostOrSales]);
                }
                // Instantiate and draw our chart, passing in some options
                var chart = new window.google.visualization.PieChart(document.getElementById('chart_div'));

                chart.draw(data,
                  {
                      title: "Statistics sectional managers",
                      position: "center",
                      fontsize: "14px",
                      chartArea: { width: '50%' }
                  });
            }
      
</script>
<div id="chart_div" style=" height: 350px;"></div>